// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using aspnetcoreapp;

namespace aspnetcoreapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201201064828_seeder2")]
    partial class seeder2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("aspnetcoreapp.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dev",
                            Price = 10m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 2,
                            Name = "Banana",
                            Price = 5m,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("aspnetcoreapp.Models.DroneLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("Latitude")
                        .HasColumnType("integer");

                    b.Property<int>("Longitude")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("RegionName")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("DroneLogs");

                    b.HasData(
                        new
                        {
                            EntityLogPrimaryKeyId = 10,
                            Description = "Drone Delete",
                            EntityId = 0,
                            Latitude = 32,
                            Longitude = 39,
                            Name = "Drone FI",
                            RegionName = "EPNXG",
                            Timestamp = new DateTime(2020, 12, 1, 7, 33, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 11,
                            Description = "Drone Add",
                            EntityId = 2,
                            Latitude = 37,
                            Longitude = 19,
                            Name = "Drone UI",
                            RegionName = "WUWYA",
                            Timestamp = new DateTime(2020, 12, 2, 6, 44, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 12,
                            Description = "Drone Add",
                            EntityId = 4,
                            Latitude = 25,
                            Longitude = 39,
                            Name = "Drone OM",
                            RegionName = "KFDKW",
                            Timestamp = new DateTime(2020, 12, 2, 15, 19, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 13,
                            Description = "Drone Edit",
                            EntityId = 6,
                            Latitude = 33,
                            Longitude = 24,
                            Name = "Drone VD",
                            RegionName = "VQMSC",
                            Timestamp = new DateTime(2020, 12, 1, 17, 13, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 14,
                            Description = "Drone Edit",
                            EntityId = 8,
                            Latitude = 40,
                            Longitude = 22,
                            Name = "Drone IC",
                            RegionName = "BKHIZ",
                            Timestamp = new DateTime(2020, 12, 1, 12, 36, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 15,
                            Description = "Drone Add",
                            EntityId = 10,
                            Latitude = 44,
                            Longitude = 33,
                            Name = "Drone TC",
                            RegionName = "SYUAX",
                            Timestamp = new DateTime(2020, 12, 1, 9, 36, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 16,
                            Description = "Drone Delete",
                            EntityId = 12,
                            Latitude = 23,
                            Longitude = 34,
                            Name = "Drone XQ",
                            RegionName = "HWGSK",
                            Timestamp = new DateTime(2020, 12, 1, 14, 12, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 17,
                            Description = "Drone Delete",
                            EntityId = 14,
                            Latitude = 36,
                            Longitude = 42,
                            Name = "Drone PY",
                            RegionName = "DWBQS",
                            Timestamp = new DateTime(2020, 12, 1, 5, 35, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 18,
                            Description = "Drone Add",
                            EntityId = 16,
                            Latitude = 38,
                            Longitude = 17,
                            Name = "Drone AD",
                            RegionName = "RWXPN",
                            Timestamp = new DateTime(2020, 12, 2, 14, 31, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 19,
                            Description = "Drone Add",
                            EntityId = 18,
                            Latitude = 17,
                            Longitude = 23,
                            Name = "Drone MT",
                            RegionName = "CCRXT",
                            Timestamp = new DateTime(2020, 12, 2, 15, 36, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 20,
                            Description = "Drone Add",
                            EntityId = 20,
                            Latitude = 41,
                            Longitude = 25,
                            Name = "Drone LP",
                            RegionName = "OCLGP",
                            Timestamp = new DateTime(2020, 12, 2, 1, 9, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 21,
                            Description = "Drone Add",
                            EntityId = 22,
                            Latitude = 19,
                            Longitude = 23,
                            Name = "Drone MH",
                            RegionName = "UQFCG",
                            Timestamp = new DateTime(2020, 12, 1, 12, 44, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 22,
                            Description = "Drone Add",
                            EntityId = 24,
                            Latitude = 13,
                            Longitude = 16,
                            Name = "Drone MX",
                            RegionName = "AUIBW",
                            Timestamp = new DateTime(2020, 12, 1, 11, 1, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 23,
                            Description = "Drone Add",
                            EntityId = 26,
                            Latitude = 40,
                            Longitude = 26,
                            Name = "Drone SX",
                            RegionName = "TEPHF",
                            Timestamp = new DateTime(2020, 12, 1, 11, 2, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 24,
                            Description = "Drone Delete",
                            EntityId = 28,
                            Latitude = 40,
                            Longitude = 27,
                            Name = "Drone SL",
                            RegionName = "CZCQE",
                            Timestamp = new DateTime(2020, 12, 2, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 25,
                            Description = "Drone Add",
                            EntityId = 30,
                            Latitude = 32,
                            Longitude = 29,
                            Name = "Drone AV",
                            RegionName = "HTUWU",
                            Timestamp = new DateTime(2020, 12, 2, 1, 49, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 26,
                            Description = "Drone Delete",
                            EntityId = 32,
                            Latitude = 30,
                            Longitude = 35,
                            Name = "Drone SF",
                            RegionName = "VOWZD",
                            Timestamp = new DateTime(2020, 12, 2, 13, 27, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 27,
                            Description = "Drone Add",
                            EntityId = 34,
                            Latitude = 48,
                            Longitude = 14,
                            Name = "Drone HZ",
                            RegionName = "FENKV",
                            Timestamp = new DateTime(2020, 12, 1, 11, 22, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 28,
                            Description = "Drone Add",
                            EntityId = 36,
                            Latitude = 23,
                            Longitude = 37,
                            Name = "Drone QZ",
                            RegionName = "TOAHK",
                            Timestamp = new DateTime(2020, 12, 2, 7, 23, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 29,
                            Description = "Drone Add",
                            EntityId = 38,
                            Latitude = 32,
                            Longitude = 15,
                            Name = "Drone AM",
                            RegionName = "IBTDR",
                            Timestamp = new DateTime(2020, 12, 1, 14, 27, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 30,
                            Description = "Drone Edit",
                            EntityId = 40,
                            Latitude = 40,
                            Longitude = 27,
                            Name = "Drone YN",
                            RegionName = "IZMQW",
                            Timestamp = new DateTime(2020, 12, 1, 14, 47, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 31,
                            Description = "Drone Delete",
                            EntityId = 42,
                            Latitude = 24,
                            Longitude = 39,
                            Name = "Drone AK",
                            RegionName = "TALZF",
                            Timestamp = new DateTime(2020, 12, 2, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 32,
                            Description = "Drone Edit",
                            EntityId = 44,
                            Latitude = 40,
                            Longitude = 40,
                            Name = "Drone OF",
                            RegionName = "UTDFA",
                            Timestamp = new DateTime(2020, 12, 1, 12, 16, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 33,
                            Description = "Drone Add",
                            EntityId = 46,
                            Latitude = 28,
                            Longitude = 14,
                            Name = "Drone CJ",
                            RegionName = "POQBY",
                            Timestamp = new DateTime(2020, 12, 1, 2, 25, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 34,
                            Description = "Drone Add",
                            EntityId = 48,
                            Latitude = 36,
                            Longitude = 42,
                            Name = "Drone IF",
                            RegionName = "RUCWV",
                            Timestamp = new DateTime(2020, 12, 1, 3, 4, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 35,
                            Description = "Drone Edit",
                            EntityId = 50,
                            Latitude = 13,
                            Longitude = 14,
                            Name = "Drone ZD",
                            RegionName = "BROJF",
                            Timestamp = new DateTime(2020, 12, 2, 14, 13, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 36,
                            Description = "Drone Add",
                            EntityId = 52,
                            Latitude = 27,
                            Longitude = 20,
                            Name = "Drone HS",
                            RegionName = "QUJYW",
                            Timestamp = new DateTime(2020, 12, 2, 9, 22, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 37,
                            Description = "Drone Edit",
                            EntityId = 54,
                            Latitude = 13,
                            Longitude = 46,
                            Name = "Drone LK",
                            RegionName = "UIAHH",
                            Timestamp = new DateTime(2020, 12, 2, 14, 38, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 38,
                            Description = "Drone Delete",
                            EntityId = 56,
                            Latitude = 18,
                            Longitude = 36,
                            Name = "Drone OD",
                            RegionName = "QGHKX",
                            Timestamp = new DateTime(2020, 12, 2, 4, 5, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 39,
                            Description = "Drone Delete",
                            EntityId = 58,
                            Latitude = 32,
                            Longitude = 22,
                            Name = "Drone VY",
                            RegionName = "NIDIZ",
                            Timestamp = new DateTime(2020, 12, 2, 2, 35, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 40,
                            Description = "Drone Delete",
                            EntityId = 60,
                            Latitude = 27,
                            Longitude = 38,
                            Name = "Drone LI",
                            RegionName = "LILET",
                            Timestamp = new DateTime(2020, 12, 1, 5, 4, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 41,
                            Description = "Drone Delete",
                            EntityId = 62,
                            Latitude = 48,
                            Longitude = 47,
                            Name = "Drone XM",
                            RegionName = "CIBMH",
                            Timestamp = new DateTime(2020, 12, 1, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 42,
                            Description = "Drone Delete",
                            EntityId = 64,
                            Latitude = 19,
                            Longitude = 44,
                            Name = "Drone TK",
                            RegionName = "GYTYS",
                            Timestamp = new DateTime(2020, 12, 2, 4, 16, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 43,
                            Description = "Drone Add",
                            EntityId = 66,
                            Latitude = 29,
                            Longitude = 11,
                            Name = "Drone JU",
                            RegionName = "QXKND",
                            Timestamp = new DateTime(2020, 12, 2, 5, 44, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 44,
                            Description = "Drone Edit",
                            EntityId = 68,
                            Latitude = 31,
                            Longitude = 30,
                            Name = "Drone GW",
                            RegionName = "JLWZZ",
                            Timestamp = new DateTime(2020, 12, 2, 6, 21, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 45,
                            Description = "Drone Add",
                            EntityId = 70,
                            Latitude = 49,
                            Longitude = 44,
                            Name = "Drone RD",
                            RegionName = "XWHPN",
                            Timestamp = new DateTime(2020, 12, 1, 2, 43, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 46,
                            Description = "Drone Delete",
                            EntityId = 72,
                            Latitude = 40,
                            Longitude = 44,
                            Name = "Drone ZX",
                            RegionName = "VMCAC",
                            Timestamp = new DateTime(2020, 12, 1, 2, 34, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 47,
                            Description = "Drone Edit",
                            EntityId = 74,
                            Latitude = 39,
                            Longitude = 18,
                            Name = "Drone VH",
                            RegionName = "XJNWB",
                            Timestamp = new DateTime(2020, 12, 2, 8, 49, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 48,
                            Description = "Drone Edit",
                            EntityId = 76,
                            Latitude = 15,
                            Longitude = 48,
                            Name = "Drone NQ",
                            RegionName = "NCDWB",
                            Timestamp = new DateTime(2020, 12, 1, 9, 40, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 49,
                            Description = "Drone Add",
                            EntityId = 78,
                            Latitude = 23,
                            Longitude = 39,
                            Name = "Drone VO",
                            RegionName = "BNBVL",
                            Timestamp = new DateTime(2020, 12, 1, 16, 43, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        });
                });

            modelBuilder.Entity("aspnetcoreapp.Models.ImageLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("ImageLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.IncidentLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("IncidentLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.MonitorRegionLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("MonitorRegionLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.ObjectObserve", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("ObjectObserve");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.Payload", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("Payload");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.ResolveProblemLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("ResolveProblemLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.StaticalLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("StaticalLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.UavConnectLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("UavConnectLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.UserLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("UserLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.VideoLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("VideoLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.WarningLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("WarningLog");
                });
#pragma warning restore 612, 618
        }
    }
}
