// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using aspnetcoreapp;

namespace aspnetcoreapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201201065354_seeder3")]
    partial class seeder3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("aspnetcoreapp.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dev",
                            Price = 10m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 2,
                            Name = "Banana",
                            Price = 5m,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("aspnetcoreapp.Models.DroneLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("Latitude")
                        .HasColumnType("integer");

                    b.Property<int>("Longitude")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("RegionName")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("DroneLogs");

                    b.HasData(
                        new
                        {
                            EntityLogPrimaryKeyId = 10,
                            Description = "Drone Delete",
                            EntityId = 0,
                            Latitude = 47,
                            Longitude = 29,
                            Name = "Drone CE",
                            RegionName = "OKLKL",
                            Timestamp = new DateTime(2020, 12, 1, 5, 14, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 11,
                            Description = "Drone Delete",
                            EntityId = 2,
                            Latitude = 43,
                            Longitude = 31,
                            Name = "Drone OF",
                            RegionName = "ASNPD",
                            Timestamp = new DateTime(2020, 12, 2, 8, 13, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 12,
                            Description = "Drone Edit",
                            EntityId = 4,
                            Latitude = 19,
                            Longitude = 37,
                            Name = "Drone OO",
                            RegionName = "UACJK",
                            Timestamp = new DateTime(2020, 12, 2, 1, 33, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 13,
                            Description = "Drone Add",
                            EntityId = 6,
                            Latitude = 27,
                            Longitude = 32,
                            Name = "Drone AP",
                            RegionName = "VTLRJ",
                            Timestamp = new DateTime(2020, 12, 1, 5, 40, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 14,
                            Description = "Drone Edit",
                            EntityId = 8,
                            Latitude = 44,
                            Longitude = 37,
                            Name = "Drone NL",
                            RegionName = "KWKYF",
                            Timestamp = new DateTime(2020, 12, 1, 7, 32, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 15,
                            Description = "Drone Add",
                            EntityId = 10,
                            Latitude = 43,
                            Longitude = 21,
                            Name = "Drone GC",
                            RegionName = "RKETV",
                            Timestamp = new DateTime(2020, 12, 1, 4, 15, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 16,
                            Description = "Drone Edit",
                            EntityId = 12,
                            Latitude = 22,
                            Longitude = 48,
                            Name = "Drone QB",
                            RegionName = "PJFAU",
                            Timestamp = new DateTime(2020, 12, 2, 12, 3, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 17,
                            Description = "Drone Edit",
                            EntityId = 14,
                            Latitude = 40,
                            Longitude = 25,
                            Name = "Drone MB",
                            RegionName = "VLPRQ",
                            Timestamp = new DateTime(2020, 12, 2, 14, 5, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 18,
                            Description = "Drone Add",
                            EntityId = 16,
                            Latitude = 10,
                            Longitude = 35,
                            Name = "Drone GM",
                            RegionName = "COEHD",
                            Timestamp = new DateTime(2020, 12, 1, 8, 21, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 19,
                            Description = "Drone Add",
                            EntityId = 18,
                            Latitude = 27,
                            Longitude = 38,
                            Name = "Drone UF",
                            RegionName = "OARZK",
                            Timestamp = new DateTime(2020, 12, 1, 4, 46, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 20,
                            Description = "Drone Delete",
                            EntityId = 20,
                            Latitude = 31,
                            Longitude = 35,
                            Name = "Drone PE",
                            RegionName = "QMCZV",
                            Timestamp = new DateTime(2020, 12, 1, 15, 14, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 21,
                            Description = "Drone Edit",
                            EntityId = 22,
                            Latitude = 19,
                            Longitude = 26,
                            Name = "Drone TL",
                            RegionName = "VKDUY",
                            Timestamp = new DateTime(2020, 12, 2, 11, 21, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 22,
                            Description = "Drone Add",
                            EntityId = 24,
                            Latitude = 32,
                            Longitude = 42,
                            Name = "Drone VV",
                            RegionName = "IDRGB",
                            Timestamp = new DateTime(2020, 12, 2, 3, 21, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 23,
                            Description = "Drone Delete",
                            EntityId = 26,
                            Latitude = 20,
                            Longitude = 46,
                            Name = "Drone BO",
                            RegionName = "WYLUY",
                            Timestamp = new DateTime(2020, 12, 2, 17, 18, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 24,
                            Description = "Drone Add",
                            EntityId = 28,
                            Latitude = 12,
                            Longitude = 18,
                            Name = "Drone BF",
                            RegionName = "FAAEK",
                            Timestamp = new DateTime(2020, 12, 1, 3, 2, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 25,
                            Description = "Drone Delete",
                            EntityId = 30,
                            Latitude = 18,
                            Longitude = 20,
                            Name = "Drone RI",
                            RegionName = "KKLTC",
                            Timestamp = new DateTime(2020, 12, 2, 17, 31, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 26,
                            Description = "Drone Edit",
                            EntityId = 32,
                            Latitude = 14,
                            Longitude = 10,
                            Name = "Drone ZM",
                            RegionName = "OMQHD",
                            Timestamp = new DateTime(2020, 12, 2, 5, 43, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 27,
                            Description = "Drone Edit",
                            EntityId = 34,
                            Latitude = 37,
                            Longitude = 21,
                            Name = "Drone JV",
                            RegionName = "QTDWE",
                            Timestamp = new DateTime(2020, 12, 2, 7, 26, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 28,
                            Description = "Drone Edit",
                            EntityId = 36,
                            Latitude = 24,
                            Longitude = 43,
                            Name = "Drone HT",
                            RegionName = "VCPYS",
                            Timestamp = new DateTime(2020, 12, 1, 7, 43, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 29,
                            Description = "Drone Add",
                            EntityId = 38,
                            Latitude = 18,
                            Longitude = 41,
                            Name = "Drone BG",
                            RegionName = "XDWRJ",
                            Timestamp = new DateTime(2020, 12, 1, 17, 43, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 30,
                            Description = "Drone Add",
                            EntityId = 40,
                            Latitude = 30,
                            Longitude = 25,
                            Name = "Drone HX",
                            RegionName = "QPFLK",
                            Timestamp = new DateTime(2020, 12, 1, 15, 33, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 31,
                            Description = "Drone Add",
                            EntityId = 42,
                            Latitude = 23,
                            Longitude = 42,
                            Name = "Drone JI",
                            RegionName = "NENRY",
                            Timestamp = new DateTime(2020, 12, 1, 15, 11, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 32,
                            Description = "Drone Add",
                            EntityId = 44,
                            Latitude = 48,
                            Longitude = 31,
                            Name = "Drone KD",
                            RegionName = "PRXAC",
                            Timestamp = new DateTime(2020, 12, 2, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 33,
                            Description = "Drone Add",
                            EntityId = 46,
                            Latitude = 31,
                            Longitude = 48,
                            Name = "Drone VM",
                            RegionName = "SJJZC",
                            Timestamp = new DateTime(2020, 12, 1, 5, 16, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 34,
                            Description = "Drone Delete",
                            EntityId = 48,
                            Latitude = 48,
                            Longitude = 39,
                            Name = "Drone JJ",
                            RegionName = "MYGOD",
                            Timestamp = new DateTime(2020, 12, 1, 9, 33, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 35,
                            Description = "Drone Delete",
                            EntityId = 50,
                            Latitude = 18,
                            Longitude = 10,
                            Name = "Drone CI",
                            RegionName = "EJKNT",
                            Timestamp = new DateTime(2020, 12, 2, 5, 34, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 36,
                            Description = "Drone Delete",
                            EntityId = 52,
                            Latitude = 27,
                            Longitude = 42,
                            Name = "Drone FC",
                            RegionName = "VWBRE",
                            Timestamp = new DateTime(2020, 12, 2, 2, 21, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 37,
                            Description = "Drone Add",
                            EntityId = 54,
                            Latitude = 39,
                            Longitude = 45,
                            Name = "Drone YD",
                            RegionName = "MYTBX",
                            Timestamp = new DateTime(2020, 12, 2, 11, 17, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 38,
                            Description = "Drone Edit",
                            EntityId = 56,
                            Latitude = 45,
                            Longitude = 33,
                            Name = "Drone TW",
                            RegionName = "SYEZC",
                            Timestamp = new DateTime(2020, 12, 1, 3, 9, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 39,
                            Description = "Drone Add",
                            EntityId = 58,
                            Latitude = 42,
                            Longitude = 31,
                            Name = "Drone PN",
                            RegionName = "IJWSZ",
                            Timestamp = new DateTime(2020, 12, 1, 4, 44, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 40,
                            Description = "Drone Delete",
                            EntityId = 60,
                            Latitude = 19,
                            Longitude = 22,
                            Name = "Drone UK",
                            RegionName = "AVEGU",
                            Timestamp = new DateTime(2020, 12, 2, 12, 17, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 41,
                            Description = "Drone Add",
                            EntityId = 62,
                            Latitude = 41,
                            Longitude = 26,
                            Name = "Drone HR",
                            RegionName = "VACFQ",
                            Timestamp = new DateTime(2020, 12, 2, 4, 35, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 42,
                            Description = "Drone Add",
                            EntityId = 64,
                            Latitude = 22,
                            Longitude = 48,
                            Name = "Drone IL",
                            RegionName = "GSVVX",
                            Timestamp = new DateTime(2020, 12, 2, 3, 1, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 43,
                            Description = "Drone Add",
                            EntityId = 66,
                            Latitude = 16,
                            Longitude = 32,
                            Name = "Drone KG",
                            RegionName = "ZVJVJ",
                            Timestamp = new DateTime(2020, 12, 2, 10, 37, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 44,
                            Description = "Drone Edit",
                            EntityId = 68,
                            Latitude = 35,
                            Longitude = 48,
                            Name = "Drone WX",
                            RegionName = "LCBBU",
                            Timestamp = new DateTime(2020, 12, 2, 17, 29, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 45,
                            Description = "Drone Edit",
                            EntityId = 70,
                            Latitude = 25,
                            Longitude = 31,
                            Name = "Drone RP",
                            RegionName = "OXECR",
                            Timestamp = new DateTime(2020, 12, 1, 6, 39, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 46,
                            Description = "Drone Add",
                            EntityId = 72,
                            Latitude = 37,
                            Longitude = 14,
                            Name = "Drone ST",
                            RegionName = "RQMGU",
                            Timestamp = new DateTime(2020, 12, 2, 7, 43, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 47,
                            Description = "Drone Edit",
                            EntityId = 74,
                            Latitude = 14,
                            Longitude = 43,
                            Name = "Drone PY",
                            RegionName = "JCHZL",
                            Timestamp = new DateTime(2020, 12, 1, 14, 10, 0, 0, DateTimeKind.Unspecified),
                            Type = 4
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 48,
                            Description = "Drone Delete",
                            EntityId = 76,
                            Latitude = 22,
                            Longitude = 12,
                            Name = "Drone PL",
                            RegionName = "TFTOG",
                            Timestamp = new DateTime(2020, 12, 2, 16, 28, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            EntityLogPrimaryKeyId = 49,
                            Description = "Drone Delete",
                            EntityId = 78,
                            Latitude = 46,
                            Longitude = 48,
                            Name = "Drone JK",
                            RegionName = "VXHZE",
                            Timestamp = new DateTime(2020, 12, 2, 3, 43, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        });
                });

            modelBuilder.Entity("aspnetcoreapp.Models.ImageLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("ImageLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.IncidentLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("IncidentLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.MonitorRegionLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("MonitorRegionLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.ObjectObserve", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("ObjectObserve");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.Payload", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("Payload");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.ResolveProblemLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("ResolveProblemLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.StaticalLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("StaticalLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.UavConnectLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("UavConnectLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.UserLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("UserLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.VideoLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("VideoLog");
                });

            modelBuilder.Entity("aspnetcoreapp.Models.WarningLog", b =>
                {
                    b.Property<int>("EntityLogPrimaryKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EntityLogPrimaryKeyId");

                    b.ToTable("WarningLog");
                });
#pragma warning restore 612, 618
        }
    }
}
